#ifndef __USBD_MULTI_USRCFG_LINKFEAT_HID_H__
#define __USBD_MULTI_USRCFG_LINKFEAT_HID_H__
// link feat define for usbd_multi_usrcfg_custom.c
#if defined(CHK_LINK_FEAT_USB_BUILD_ADDHID)

#else
#error "CHK_LINK_FEAT_USB_BUILD_ADDHID not defined, include linkfeat_usb_build_opt.h before include this file"
#endif

#define HID_CCINST_DISABLE  0

#define HID_CCINST_MOUSE_ONLY  1
#define HID_CCINST_KEYBOARD_ONLY  2
#define HID_CCINST_KEYBOARD_AND_MOUSE  3


#if CHK_LINK_FEAT_USB_BUILD_ADDHID


//#define HID_CCINST_CASE_SEL HID_CCINST_DISABLE
// #define HID_CCINST_CASE_SEL  HID_CCINST_MOUSE_ONLY
#define HID_CCINST_CASE_SEL  HID_CCINST_KEYBOARD_ONLY

#if (HID_CCINST_CASE_SEL==HID_CCINST_DISABLE)
#define HID_CCINST_SUBTP0_INHRNT_KEYBOARD_CNT 0
#define HID_CCINST_SUBTP0_INHRNT_MOUSE_CNT 0
#elif (HID_CCINST_CASE_SEL==HID_CCINST_MOUSE_ONLY)
#define HID_CCINST_SUBTP0_INHRNT_KEYBOARD_CNT 0
#define HID_CCINST_SUBTP0_INHRNT_MOUSE_CNT 1
#elif (HID_CCINST_CASE_SEL==HID_CCINST_KEYBOARD_ONLY)
#define HID_CCINST_SUBTP0_INHRNT_KEYBOARD_CNT 1
#define HID_CCINST_SUBTP0_INHRNT_MOUSE_CNT 0
#elif (HID_CCINST_CASE_SEL==HID_CCINST_KEYBOARD_AND_MOUSE)
#define HID_CCINST_SUBTP0_INHRNT_KEYBOARD_CNT 1
#define HID_CCINST_SUBTP0_INHRNT_MOUSE_CNT 1

#endif

#else
#define HID_CCINST_CASE_SEL HID_CCINST_DISABLE
#define HID_CCINST_SUBTP0_INHRNT_KEYBOARD_CNT 0
#define HID_CCINST_SUBTP0_INHRNT_MOUSE_CNT 0

#endif

#endif

