//  Auto generated. Don't edit it manually!

#define QOSA_NW_BAND_CFG_TABLE    \
{    \
QOSA_NW_BAND_LTE_BAND1,    \
QOSA_NW_BAND_LTE_BAND3,    \
QOSA_NW_BAND_LTE_BAND5,    \
QOSA_NW_BAND_LTE_BAND8,    \
QOSA_NW_BAND_LTE_BAND34,    \
QOSA_NW_BAND_LTE_BAND38,    \
QOSA_NW_BAND_LTE_BAND39,    \
QOSA_NW_BAND_LTE_BAND40,    \
QOSA_NW_BAND_LTE_BAND41,    \
0}    \

#define QOSA_NW_GSM_WCDMA_SUPPORT_BAND  (0)
#define QOSA_NW_LTE_SUPPORT_BAND_1_32   (0 | 1<<(QOSA_NW_BAND_LTE_BAND1-1) | 1<<(QOSA_NW_BAND_LTE_BAND3-1) | 1<<(QOSA_NW_BAND_LTE_BAND5-1) | 1<<(QOSA_NW_BAND_LTE_BAND8-1))
#define QOSA_NW_LTE_SUPPORT_BAND_33_64  (0 | 1<<(QOSA_NW_BAND_LTE_BAND34-33) | 1<<(QOSA_NW_BAND_LTE_BAND38-33) | 1<<(QOSA_NW_BAND_LTE_BAND39-33) | 1<<(QOSA_NW_BAND_LTE_BAND40-33) | 1<<(QOSA_NW_BAND_LTE_BAND41-33))
#define QOSA_NW_LTE_SUPPORT_BAND_65_96  (0)
#define QOSA_NW_NR_SUPPORT_BAND_1_32   (0)
#define QOSA_NW_NR_SUPPORT_BAND_33_64  (0)
#define QOSA_NW_NR_SUPPORT_BAND_65_96  (0)
