/* Copyright (C) 2020 UNIRTOS Technologies Limited and/or its affiliates("UNIRTOS").
 * All rights reserved.
 */

#ifndef __QOSA_MODEM_AT_CONFIG__H__
#define __QOSA_MODEM_AT_CONFIG__H__

/* #undef CONFIG_QOSA_MODEM_AT_NW_RSSI_QCSQ_LTE_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_RSSI_QCSQ_LTE_SPEC_VAL 2

/* #undef CONFIG_QOSA_MODEM_AT_NW_RSSI_QCSQ_GSM_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_RSSI_QCSQ_GSM_SPEC_VAL 3

/* #undef CONFIG_QOSA_MODEM_AT_NW_RXLEV_QENG_GSM_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_RXLEV_QENG_GSM_SPEC_VAL 0

/* #undef CONFIG_QOSA_MODEM_AT_NW_RXLEV_QCELL_GSM_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_RXLEV_QCELL_GSM_SPEC_VAL 0

/* #undef CONFIG_QOSA_MODEM_AT_NW_RXLEV_QOPS_GSM_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_RXLEV_QOPS_GSM_SPEC_VAL 2

/* #undef CONFIG_QOSA_MODEM_AT_NW_SINR_QCSQ_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_SINR_QCSQ_SPEC_VAL 2

/* #undef CONFIG_QOSA_MODEM_AT_NW_SINR_QENG_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_SINR_QENG_SPEC_VAL 0

/* #undef CONFIG_QOSA_MODEM_AT_NW_SINR_QCELL_SPEC */
#define CONFIG_QOSA_MODEM_AT_NW_SINR_QCELL_SPEC_VAL 0

#endif /* __QOSA_MODEM_AT_CONFIG__H__ */
