/*****************************************************************/ /**
* @file coap_client.h
* @brief
* @author larson.li@quectel.com
* @date 2024-09-12
*
* @copyright Copyright (c) 2023 Quectel Wireless Solution, Co., Ltd.
* All Rights Reserved. Quectel Wireless Solution Proprietary and Confidential.
*
* @par EDIT HISTORY FOR MODULE
* <table>
* <tr><th>Date <th>Version <th>Author <th>Description"
* <tr><td>2024-09-12 <td>1.0 <td>Larson.Li <td> Init
* </table>
**********************************************************************/
#ifndef __COAP_CLIENT_H__
#define __COAP_CLIENT_H__

#include "qosa_def.h"
#include "qosa_sys.h"
#include "coap_13.h"
#include "qcm_vtls_cfg.h"

/**
 * @brief CoAP client ID type definition
 * @details Used to identify CoAP client instances, serving as handles for client operations
 */
typedef int coap_client_id;

/**
 * @brief Maximum number of context clients supported by COAP
 * @details Maximum number of CoAP client instances supported simultaneously by the system
 */
#define Q_COAP_CLIENT_MAX_NUM 4

/**
 * @brief Starting value for context clients supported by COAP
 * @details Starting number for CoAP client IDs, the minimum valid ID value
 */
#define Q_COAP_CLIENT_MIN_NUM 1

/**
 * @brief Client ID return offset value
 * @details Used to calculate the client ID returned to the user, actual ID = internal ID + offset
 */
#define Q_COAP_CLIENT_OFFSET  1

/**
 * @brief CoAP block parameter structure
 * @details Used to handle the block transfer (Block) option in the CoAP protocol, supporting large data block transfers
 */
typedef struct
{
    qosa_uint32_t num;    /*!< Block number, sequence number of the current block */
    qosa_uint8_t  more;   /*!< Whether there are more blocks, 1 means more blocks, 0 means this is the last block */
    qosa_uint16_t size;   /*!< Block size in bytes */
    qosa_uint32_t offset; /*!< Block offset, starting position in the resource */
} coap_block_param_t;

/**
 * @brief COAP client configuration parameters
 * @details Contains various configuration options required for CoAP client initialization and operation
 */
typedef struct
{
    qosa_uint8_t pdp_cid;     /*!< PDP context ID, used to identify network connections */
    qosa_uint8_t sim_cid;     /*!< SIM card context ID, used to identify SIM cards */
    qosa_time_t  max_timeout; /*!< Maximum timeout for PDP activation in milliseconds */
    qosa_uint8_t max_retry;   /*!< Maximum retry count for COAP connection and request retries */
    qosa_bool_t  is_use_dtls; /*!< Whether to use DTLS encrypted transmission, 1 means enabled, 0 means disabled */
} coap_client_cfg_t;

/**
 * @brief CoAP request status enumeration
 * @details Defines possible status results during CoAP request execution
 */
typedef enum
{
    COAP_REQUEST_STATUS_SUCCESS = 0, /*!< Request completed successfully */
    COAP_REQUEST_STATUS_FAILURE = 1, /*!< Request execution failed */
    COAP_REQUEST_STATUS_RESET = 2,   /*!< Request reset by RST message */
    COAP_REQUEST_STATUS_TIMEOUT = 3, /*!< Request timed out without receiving a response */
    COAP_REQUEST_STATUS_CANCELED = 4 /*!< Request canceled by user */
} coap_request_status_e;

/**
 * @brief CoAP client execution error codes
 * @details Defines error types that may occur during CoAP client operations
 */
typedef enum
{
    COAP_SUCCESS = 0,                /*!< Operation successful */
    COAP_ERR_INVALID_PARAM,          /*!< Invalid parameter, illegal input parameter */
    COAP_ERR_PDP_ACTIVE_FAILURE,     /*!< PDP activation failed, unable to establish network connection */
    COAP_ERR_MEMORY,                 /*!< Memory allocation failed, insufficient system resources */
    COAP_ERR_DNS_FAILURE,            /*!< DNS resolution failed, unable to resolve server domain name */
    COAP_ERR_SOCKET_CONNECT_FAILURE, /*!< Socket connection failed, unable to establish network connection */
    COAP_ERR_DTLS_HANDSHARK_FAILURE, /*!< DTLS handshake failed, failed to establish secure connection */
    COAP_ERR_SEND_ERR,               /*!< Socket send failed, data sending error */
    COAP_ERR_RECV_ERR,               /*!< Socket receive failed, data receiving error */
    COAP_ERR_RESPONSE_PARSE_ERR,     /*!< CoAP response parsing failed, incorrect response format */
    COAP_ERR_MACTH_FAILURE,          /*!< CoAP response and request matching failed, response does not match request */
    COAP_ERR_RESPONSE_TYPE_RST,      /*!< CoAP response type error, received RST response */
    COAP_ERR_SEND_RETRY_OUT,         /*!< CoAP request retry count reached limit, retry exceeded */
    COAP_ERR_UNACKED_REQUEST_MAX,    /*!< Maximum number of unacknowledged requests reached, no request space available */
} coap_result_code_e;

/**
 * @brief CoAP client event notification types
 * @details Defines event types that may be generated by CoAP clients, used for event callback notifications
 */
typedef enum
{
    OSA_COAP_MIN_EVENT = 0, /*!< Minimum event type, used for range checking */
    OSA_COAP_CONNECT_EVENT, /*!< Connection event notification, triggered when connection status changes */
    OSA_COAP_SEND_EVENT,    /*!< Send event notification, triggered when data transmission is complete */
    OSA_COAP_RESP_EVENT,    /*!< Server response event notification, triggered when server response is received */
    OSA_COAP_CLOSE_EVENT,   /*!< Close event notification, triggered when client is closed */
} coap_client_event_e;

/**
 * @brief CoAP client connection event notification structure
 * @details Used to pass related information of connection events
 */
typedef struct
{
    coap_client_id     client_id;   /*!< Client ID, identifying which client generated the event */
    coap_result_code_e result_code; /*!< Connection result, specific error code for success or failure */
} coap_connect_info_t;

/**
 * @brief CoAP client send event notification structure
 * @details Used to pass related information of data send events
 */
typedef struct
{
    coap_client_id     client_id;   /*!< Client ID, identifying which client generated the event */
    coap_result_code_e result_code; /*!< Send result, specific error code for success or failure */
} coap_send_info_t;

/**
 * @brief CoAP client response event notification structure
 * @details Used to pass related information of server response events
 */
typedef struct
{
    coap_client_id     client_id;    /*!< Client ID, identifying which client generated the event */
    coap_packet_t      resp_message; /*!< CoAP message packet from server response */
    coap_result_code_e result_code;  /*!< Response processing result, specific error code for success or failure */
} coap_response_info_t;

/**
 * @brief CoAP client close event notification structure
 * @details Used to pass related information of client close events
 */
typedef struct
{
    coap_client_id     client_id;   /*!< Client ID, identifying which client generated the event */
    coap_result_code_e result_code; /*!< Close result, specific error code for success or failure */
} coap_close_info_t;

/**
 * @struct  coap_timeout_send_t
 * @brief Used to record information of CoAP packets to be sent
 * @details Used to manage CoAP request packets to be sent, especially handling timeout retransmission scenarios
 */
typedef struct
{
    coap_client_id client_id; /*!< Client handle, identifying which client made the request */
    qosa_uint32_t  i;         /*!< Sequence number of the request message, used to identify and match requests */
} coap_timeout_send_t;

/**
 * @brief Callback function pointer declaration for CoAP client event notifications
 * @details When a CoAP client generates an event, the application is notified through this callback function
 *
 * @param[in] event_id Event type, see coap_client_event_e enumeration
 * @param[in] evt_param Event parameters, different structure contents based on event type
 * @param[in] user_param User-defined parameter, passed when creating the client
 */
typedef void (*coap_client_event_cb)(coap_client_event_e event_id, void *evt_param, void *user_param);

/**
 * @brief CoAP request completion callback function declaration
 * @details When CoAP request sending is complete or a response is received, the application is notified through this callback function
 *          Supports callback notifications for CON and NON type requests
 *
 * @param[in] client_id CoAP client ID, identifying which client made the request
 * @param[in] packet CoAP response packet pointer, containing response information from server
 * @param[in] status CoAP request status, indicating request execution result
 * @param[in] user_param User-defined parameter, passed when sending the request
 */
typedef void (*coap_request_cb)(coap_client_id client_id, coap_packet_t *packet, coap_request_status_e status, void *user_param);

/**
 * @brief Create CoAP client instance
 * @details Initialize CoAP client resources, return client operation handle
 *
 * @param[in] cb CoAP client event callback function pointer, for receiving client event notifications
 * @param[in] user_argv Callback function user parameter, will be passed to event callback function
 *
 * @return coap_client_id
 *       - Returns client ID on success, greater than 0
 *       - Returns -1 on failure
 *
 * @note Resources must be released by calling coap_client_close after use
 */
coap_client_id coap_client_create(coap_client_event_cb cb, void *user_argv);

/**
 * @brief CoAP client executes connection action
 * @details Establishes network connection with CoAP server, supports regular CoAP and DTLS encrypted connections
 *
 * @param[in] client_id CoAP client ID
 * @param[in] host CoAP server domain name or IP address
 * @param[in] port CoAP server port number, defaults to 5683 (CoAP) or 5684 (CoAPS)
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Connection successful
 *       - COAP_ERR_XXX: Connection failed, see coap_result_code_e enumeration for specific error codes
 *
 * @note Ensure network is activated before connecting, configure relevant certificates in advance if DTLS is enabled
 */
coap_result_code_e coap_client_connect(coap_client_id client_id, const char *host, qosa_uint16_t port);

/**
 * @brief CoAP client executes send action
 * @details Sends CoAP request packet to connected CoAP server
 *
 * @param[in] client_id CoAP client ID
 * @param[in] packet CoAP request packet pointer, containing request method, URI, options, payload, etc.
 * @param[in] cb Request completion callback function pointer, for receiving request results
 * @param[in] user_param Callback function user parameter, will be passed to callback function
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Send successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, such as invalid client ID or empty request packet
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 *
 * @note
 *      - If coap_request_cb function is NULL, the event callback function from client creation will be used to return message send results
 *      - Ensure client has successfully connected to server before sending
 *      - Supports CON and NON type CoAP messages
 */
coap_result_code_e coap_client_send(coap_client_id client_id, coap_packet_t *packet, coap_request_cb cb, void *user_param);

/**
 * @brief Close CoAP client and release resources
 * @details Disconnects from server and releases all resources occupied by CoAP client
 *
 * @param[in] client_id CoAP client ID
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Close successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, invalid client ID
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 *
 * @note After calling this function, the client ID will become invalid and cannot be used again
 */
coap_result_code_e coap_client_close(coap_client_id client_id);

/**
 * @brief Set CoAP client attribute configuration
 * @details Configures various parameters of CoAP client, such as timeout, retry count, whether to use DTLS, etc.
 *
 * @param[in] client_id CoAP client ID
 * @param[in] client_cfg Configuration parameter pointer, containing client configuration to be set
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Configuration successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, such as invalid client ID or NULL configuration pointer
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 *
 * @note Configuration must be set before client connection, some configurations may not be modifiable after connection
 */
coap_result_code_e coap_client_set_config(coap_client_id client_id, coap_client_cfg_t *client_cfg);

/**
 * @brief Get SSL configuration handle
 * @details Returns SSL configuration handle required for DTLS connection, can be used to set certificates, encryption algorithms, etc.
 *
 * @param[in] client_id CoAP client ID
 *
 * @return qcm_ssl_config_t*
 *       - Returns SSL configuration handle pointer on success
 *       - Returns NULL on failure
 *
 * @note The returned handle can be used for SSL configuration functions defined in qcm_vtls_cfg.h
 *       Ensure client has DTLS enabled before use
 */
qcm_ssl_config_t *coap_client_get_ssl_config(coap_client_id client_id);

/**
 * @brief Set whether to use DTLS connection
 * @details Enables or disables DTLS encrypted transmission functionality of CoAP client
 *
 * @param[in] client_id CoAP client ID
 * @param[in] is_use_dtls Whether DTLS is enabled, 1 means enabled, 0 means disabled
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Set successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, such as invalid client ID
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 *
 * @note Ensure relevant certificates and SSL parameters are properly configured before enabling DTLS
 *       This setting must be configured before client connection, modifications after connection may not take effect
 */
coap_result_code_e coap_client_set_config_dtls(coap_client_id client_id, qosa_bool_t is_use_dtls);

/**
 * @brief Get current DTLS connection status
 * @details Queries whether CoAP client currently has DTLS encrypted transmission enabled
 *
 * @param[in] client_id CoAP client ID
 * @param[out] is_use_dtls Pointer to return DTLS enabled status, 1 means enabled, 0 means disabled
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Get successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, such as invalid client ID or NULL output pointer
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 */
coap_result_code_e coap_client_get_config_dtls(coap_client_id client_id, qosa_bool_t *is_use_dtls);

/**
 * @brief Get target server information
 * @details Gets the address and port number of the currently connected CoAP server
 *
 * @param[in] client_id CoAP client ID
 * @param[out] server_name Pointer to buffer for storing server address or hostname
 * @param[out] server_port Pointer to store server port number
 *
 * @return coap_result_code_e
 *       - COAP_SUCCESS: Get successful
 *       - COAP_ERR_INVALID_PARAM: Invalid parameter, such as invalid client ID or NULL output pointer
 *       - COAP_ERR_XXX: Other errors, see coap_result_code_e enumeration for specific error codes
 *
 * @note The buffer pointed to by server_name must be large enough to hold the server address string
 *       If the client is not connected, returned information may be invalid
 */
coap_result_code_e coap_client_get_server_info(coap_client_id client_id, qosa_uint8_t *server_name, qosa_uint16_t *server_port);

#endif /* __COAP_CLIENT_H__ */
