[config]
line_0_com = COM9
agbaud = 921600
filter_embedusb = 0
filter_externcom = 1
path_convert_cfg_avail = 1
;pathconv_to_file_basedir_pairs=agentboot:agpath

[package_info]
pkgflag = 1
pkg_extract_exe = .\fcelf.exe
pkg_bins_regen_targetdir = .\pkgimg_gen
arg_pkg_path_val = .\at_command.hbinpkg
comment_inicfg_regened_state = "initial_no_change,backward_restored,forward_regened"
pkg_inicfg_regened_state = forward_regened
backward_cfg_restore_en = 1
select_product_support = 1
old_package_defined_product = EC618_OLDPKG_DEFAULT
selected_product = EC718P_PRD
selected_base_inicfg_type = usb
selected_base_inicfg_rec = ./product_sets/ec718_products/ec718p/base_config_files/config_ec718p_prd_usb.baseini@hash:dab5454ec49f8edc698eb2ac8084356cc4cb1f43c6f758f17780bdd415366948
