[config]
line_0_com = COM14
agbaud = 460800
filter_embedusb = 1
filter_externcom = 0
filter_explicitcom0 = 19D1
filter_explicitcom1 = 1366
path_convert_cfg_avail = 1
;pathconv_to_file_basedir_pairs=agentboot:agpath

[package_info]
pkgflag = 1
pkg_extract_exe = .\fcelf.exe
pkg_bins_regen_targetdir = .\pkgimg_gen
arg_pkg_path_val = .\at_command.hbinpkg
comment_inicfg_regened_state = "initial_no_change,backward_restored,forward_regened"
pkg_inicfg_regened_state = forward_regened
backward_cfg_restore_en = 1
select_product_support = 1
old_package_defined_product = EC618_OLDPKG_DEFAULT
selected_product = EC718P_PRD
selected_base_inicfg_type = uart
selected_base_inicfg_rec = ./product_sets/ec618_products/618_legacy/base_config_files/config_ec618_legacy_pkg_uart.baseini@hash:59c6ebecb2c74bf896cf2a2d93e7bb17179960c0ca45cf6873fbae6a3f6842f6
